nontippversion_CNNstriatalSegmentation('segmentation_python_code','/mnt/jxvs2_02/neil/TIPP_Demo_Copy_for_CNNProject/CodeBase/TIPP1.0/TIPP/@TIPPcustom/orig_mod_NNEval.py',...
    't1_acpc_dc_restore_brain','/mnt/jxvs2_02/neil/SBKanalysis_fromhelix/50002/T1w_acpc_dc_restore_brain.nii',...
    'nat_acpc_brainmask','/mnt/jxvs2_02/neil/SBKanalysis_fromhelix/50002/brainmask_fs.2.nii',...
    'cnn_reslice_template','/mnt/jxvs2_02/neil/TIPP_Demo_Copy_for_CNNProject/CodeBase/TIPP1.0/TIPP/@TIPPcustom/StriatalSegmentation/reslice_template.nii',...
    'segmentation_directory','/mnt/jxvs2_02/neil/TIPP_Demo_Copy_for_CNNProject/CodeBase/TIPP1.0/TIPP/@TIPPcustom/StriatalSegmentation',...
    'segmentation_intermediate_directory','/mnt/jxvs2_02/neil/SBKanalysis_fromhelix/50002',...
    'bold_template_image','/mnt/jxvs2_02/neil/SBKanalysis_fromhelix/50002/dataset/THL/THL_fMRI_3/THL_fMRI_3_nonlin_norm.nii');

% NOTE TO USER: 
% For each run where the input images change, change arguments on
% lines 2, 3, 6, & 7 above.
% For first time set-up only of this pipeline, change arguments on 
% lines 1, 4, 5, 8 above.

